### ISSUE TITLE
Ajout du vrai total d'app

### ISSUE THREAD

**Issue by sutter** [getstation/website-v3#16]
https://api.getstation.com/graphiql?query=%7B%0A%20%20servicesConnection%20%7B%0A%20%20%20%20totalCount%0A%20%20%7D%0A%7D

**Comment by sutter** [comment]
@alexstrat il me faudrait le token afin que je puisse avoir l'autorisation de fetch la data.

**Comment by alexstrat** [comment]
Normalement le « endpoint » en question est public, pas besoin de token.
Je t’avais donné un exemple dans le Slack qui utilise pas de token.
Lmk ;)
