### ISSUE TITLE
Station for Android

### ISSUE THREAD

**Issue by Jopp-gh** [getstation/website-v3#50]
Do you plan to support Android as well?
would be useful and a "nice to have"

**Comment by magne4000** [comment]
Sadly no, for the following reasons reasons:
- Station is in maintenance mode, mostly entirely thanks to @viktor44
- Current architecture is not compatible with mobile Operationg Systems. It would mean a 95% rewrite of the app to support mobile platforms (which took several years to develop by a team of 4 to 6 people)
